server:
  port: 8762

spring:
  application:
    name: zuul-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

USER_PATH:  /user
ADMIN_PATH:  /admin
PERMIT_ALL_PATH:  /, /h2-console/**
