CREATE
	TABLE
		IF NOT EXISTS MENU (ID SERIAL PRIMARY KEY,
		NAME VARCHAR(255),
		COMPONENT_NAME VARCHAR(255) ,
		GROUPS_ID BIGINT,
		PATH VARCHAR(255),
        FOREIGN KEY (GROUPS_ID) REFERENCES GROUPS (ID)
);

INSERT INTO MENU(NAME, COMPONENT_NAME, PATH) VALUES ('MASTER_TABLES', 'CORE_API', 'PATH_NAME');
INSERT INTO MENU(NAME, COMPONENT_NAME, PATH) VALUES ('INVENTORY', 'INV_API', 'PATH_NAME');
INSERT INTO MENU(NAME, COMPONENT_NAME, PATH) VALUES ('API_HISTORY_LOG', 'LOGS', 'PATH_NAME');
INSERT INTO MENU(NAME, COMPONENT_NAME, PATH) VALUES ('SECURITY_MANAGEMENT', 'COMP_NAME', 'PATH_NAME');

INSERT INTO MENU(NAME, COMPONENT_NAME, GROUPS_ID, PATH) VALUES ('MASTER_TABLES', 'CORE_API', 1, 'PATH_NAME'),
('INVENTORY', 'INV_API', 1, 'PATH_NAME'),
('API_HISTORY_LOG', 'LOGS', 1, 'PATH_NAME'),
('SECURITY_MANAGEMENT', 'COMP_NAME', 1, 'PATH_NAME');